# Generated by Django 3.2.25 on 2026-08-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='Número de identificación (V-12345678)', max_length=15, null=True, verbose_name='Cédula'),
        ),
    ]
