# Generated by Django 3.2.25 on 2026-08-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_users', '0002_auto_20260813_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=0, help_text='Número de identificación (V-12345678)', max_length=15, verbose_name='Cédula'),
            preserve_default=False,
        ),
    ]
