# Generated by Django 3.2.25 on 2026-08-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_users', '0003_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(help_text='Número de identificación (V-12345678)', max_length=15, unique=True, verbose_name='Cédula'),
        ),
    ]
