# Generated by Django 3.2.25 on 2026-09-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Crónica')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Resumen o Bajada')),
                ('content', models.TextField(verbose_name='Contenido Completo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chronicles_img/', verbose_name='Imagen Destacada')),
                ('author', models.CharField(default='Cronista Oficial', max_length=150, verbose_name='Autor / Cronista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Publicado?')),
            ],
            options={
                'verbose_name': 'Crónica',
                'verbose_name_plural': 'Crónicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo Institucional')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Titular')),
                ('descripcion', models.TextField(verbose_name='Descripción o Funciones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estructura_directiva/', verbose_name='Fotografía')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Estructura Directiva',
                'verbose_name_plural': 'Estructura Directiva',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('content_type', models.CharField(choices=[('COUNCILOR', 'Councilor'), ('NEWS', 'News'), ('CAROUSEL', 'Carousel'), ('ABOUT_US', 'About Us')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
            ],
            options={
                'verbose_name': 'Home Content',
                'verbose_name_plural': 'Home Contents',
                'ordering': ['content_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título (Ej. I Legislatura)')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período (Ej. 1992 - 1995)')),
                ('descripcion_concejales', models.TextField(verbose_name='Concejales Integrantes / Datos')),
                ('es_actual', models.BooleanField(default=False, verbose_name='¿Es la legislatura actual?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Aparición')),
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='HomeCarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumen / Tráiler')),
                ('content', models.TextField(blank=True, help_text='Texto completo para la vista de detalle', null=True, verbose_name='Contenido Completo')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en Portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='news_pdfs/', verbose_name='Documento PDF de Respaldo')),
                ('show_pdf_inline', models.BooleanField(default=False, verbose_name='¿Mostrar PDF en visor interactivo?')),
                ('social_media_url', models.URLField(blank=True, null=True, verbose_name='Enlace de Red Social (Instagram, Facebook, TikTok)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Councilor',
            fields=[
            ],
            options={
                'verbose_name': 'Councilor',
                'verbose_name_plural': 'Councilors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
    ]
