# Generated by Django 3.2.25 on 2026-09-21 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número de Comisión')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Comisión')),
                ('description', models.TextField(verbose_name='Área de Trabajo')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título (Ej. VIII Legislatura)')),
                ('period', models.CharField(max_length=50, verbose_name='Período (Ej. 2021 - 2025)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Reseña')),
                ('is_current', models.BooleanField(default=False, verbose_name='¿Es la legislatura actual?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Aparición')),
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Legislador')),
                ('party', models.CharField(blank=True, max_length=100, verbose_name='Partido / Organización')),
                ('legislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.legislature', verbose_name='Legislatura')),
            ],
            options={
                'verbose_name': 'Legislador',
                'verbose_name_plural': 'Legisladores',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('content_type', models.CharField(choices=[('NEWS', 'Noticia'), ('CHRONICLE', 'Crónica Digital'), ('CAROUSEL', 'Item de Carrusel'), ('ABOUT_US', 'Información Institucional'), ('COUNCILOR', 'Concejal / Directivo')], default='NEWS', max_length=20, verbose_name='Tipo de Contenido')),
                ('title', models.CharField(max_length=255, verbose_name='Título / Nombre Completo')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('author', models.CharField(default='Concejo Municipal', max_length=150, verbose_name='Autor / Cargo')),
                ('summary', models.TextField(blank=True, verbose_name='Resumen / Bajada')),
                ('content', models.TextField(blank=True, verbose_name='Contenido Extenso')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Corta (Compatibilidad)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/%Y/%m/', verbose_name='Imagen Principal')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='home/docs/%Y/%m/', verbose_name='Archivo Adjunto General')),
                ('pdf_file', models.FileField(blank=True, help_text='Cargue aquí la Gaceta Oficial, Ordenanza o documento en PDF respaldatorio.', null=True, upload_to='news_pdfs/%Y/%m/', verbose_name='Documento PDF Adjunto')),
                ('show_pdf_inline', models.BooleanField(default=False, help_text='Si está marcado, el PDF se mostrará incrustado directamente en la vista de la noticia.', verbose_name='Mostrar visor de PDF incrustado')),
                ('social_media_url', models.URLField(blank=True, null=True, verbose_name='Enlace de Red Social / Web')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='PUBLISHED', max_length=10, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de Aparición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_home_contents', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Contenido del Home',
                'verbose_name_plural': 'Contenidos del Home',
                'ordering': ['content_type', 'order', '-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
            ],
            options={
                'verbose_name': 'Item de Carrusel',
                'verbose_name_plural': 'Items del Carrusel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
            ],
            options={
                'verbose_name': 'Crónica Digital',
                'verbose_name_plural': 'Crónicas Digitales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Councilor',
            fields=[
            ],
            options={
                'verbose_name': 'Concejal / Directivo',
                'verbose_name_plural': 'Concejales y Directiva',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
    ]
