# Generated by Django 3.2.25 on 2026-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Extracto / Resumen')),
                ('image', models.ImageField(upload_to='home/carousel/', verbose_name='Imagen del Carrusel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia de Carrusel',
                'verbose_name_plural': 'Noticias de Carrusel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalChronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Crónica')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/chronicles/', verbose_name='Imagen ilustrativa')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crónica Municipal',
                'verbose_name_plural': 'Crónicas Municipales',
                'ordering': ['-publication_date'],
            },
        ),
    ]
