# Generated by Django 3.2.25 on 2026-10-01 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_home_contents', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='commission',
            name='president',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_president', to='core.homecontent', verbose_name='Presidente de la Comisión'),
        ),
        migrations.AddField(
            model_name='commission',
            name='vice_president',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_vicepresident', to='core.homecontent', verbose_name='Vicepresidente de la Comisión'),
        ),
        migrations.AddField(
            model_name='commission',
            name='vocal',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_vocal', to='core.homecontent', verbose_name='Vocal de la Comisión'),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
            ],
            options={
                'verbose_name': 'Información Institucional',
                'verbose_name_plural': 'Información Institucional',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
            ],
            options={
                'verbose_name': 'Junta Directiva',
                'verbose_name_plural': 'Junta Directiva',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
            ],
            options={
                'verbose_name': 'Item de Carrusel',
                'verbose_name_plural': 'Items del Carrusel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
            ],
            options={
                'verbose_name': 'Crónica Digital',
                'verbose_name_plural': 'Crónicas Digitales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Councilor',
            fields=[
            ],
            options={
                'verbose_name': 'Concejal / Directivo',
                'verbose_name_plural': 'Concejales y Directiva',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
    ]
