# Generated by Django 3.2.25 on 2026-09-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['number'], 'verbose_name': 'Comisión Permanente', 'verbose_name_plural': 'Comisiones Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='legislator',
            options={'verbose_name': 'Legislador Histórico', 'verbose_name_plural': 'Legisladores Históricos'},
        ),
        migrations.AlterModelOptions(
            name='legislature',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Legislatura Histórica', 'verbose_name_plural': 'Legislaturas Históricas'},
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='commission',
            name='president',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_president', to='core.homecontent', verbose_name='Presidente de la Comisión'),
        ),
        migrations.AddField(
            model_name='commission',
            name='vice_president',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_vicepresident', to='core.homecontent', verbose_name='Vicepresidente de la Comisión'),
        ),
        migrations.AddField(
            model_name='commission',
            name='vocal',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type': 'COUNCILOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_as_vocal', to='core.homecontent', verbose_name='Vocal de la Comisión'),
        ),
        migrations.AddField(
            model_name='legislator',
            name='role',
            field=models.CharField(default='Concejal', max_length=100, verbose_name='Cargo ocupado'),
        ),
        migrations.AddField(
            model_name='legislature',
            name='mayor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Alcalde del Período'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Área de Trabajo / Funciones'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre de la Comisión'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='author',
            field=models.CharField(default='Concejo Municipal', max_length=150, verbose_name='Autor / Cargo o Partido'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido Extenso / Trayectoria'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/%Y/%m/', verbose_name='Imagen / Foto Oficial'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='show_pdf_inline',
            field=models.BooleanField(default=False, help_text='Si está marcado, el PDF se mostrará incrustado directamente en la vista.', verbose_name='Mostrar visor de PDF incrustado'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Resumen / Bajada / Biografía Corta'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(blank=True, max_length=100, verbose_name='Partido / Organización Política'),
        ),
        migrations.AlterField(
            model_name='legislature',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción / Hitos del Período'),
        ),
    ]
