# Generated by Django 3.2.25 on 2026-09-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='homecarouselnews',
            options={},
        ),
        migrations.AddField(
            model_name='homecarouselnews',
            name='content',
            field=models.TextField(blank=True, help_text='Texto completo para la vista de detalle', null=True, verbose_name='Contenido Completo'),
        ),
        migrations.AlterField(
            model_name='homecarouselnews',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='homecarouselnews',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo en Portada'),
        ),
        migrations.AlterField(
            model_name='homecarouselnews',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='homecarouselnews',
            name='summary',
            field=models.TextField(verbose_name='Resumen / Tráiler'),
        ),
        migrations.AddField(
            model_name='homecarouselnews',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Categoría'),
        ),
    ]
