# Generated by Django 3.2.25 on 2026-09-22 19:48
from django.db import migrations
from django.utils.text import slugify


def populate_council_data(apps, schema_editor):
    HomeContent = apps.get_model('core', 'HomeContent')
    Commission = apps.get_model('core', 'Commission')
    Legislature = apps.get_model('core', 'Legislature')
    Legislator = apps.get_model('core', 'Legislator')

    # 1. Carga de Concejales y Directiva 2026 (8 funcionarios)
    councilors_data = [
        {'title': 'Danny Carrillo', 'author': 'Presidente del Concejo Municipal', 'summary': 'Presidente del Concejo Municipal de Junín (Periodo 2026).', 'order': 1},
        {'title': 'Favio Omaña', 'author': 'Vicepresidente del Concejo Municipal', 'summary': 'Vicepresidente del Concejo Municipal de Junín (Periodo 2026).', 'order': 2},
        {'title': 'Isleny Caicedo', 'author': 'Secretaria Municipal', 'summary': 'Secretaria del Concejo Municipal de Junín.', 'order': 3},
        {'title': 'Juana Parada', 'author': 'Concejal Principal', 'summary': 'Concejal Principal del Municipio Junín.', 'order': 4},
        {'title': 'Arfilio Jaimes', 'author': 'Concejal Principal', 'summary': 'Concejal Principal del Municipio Junín.', 'order': 5},
        {'title': 'Ninfa Correa', 'author': 'Concejal Principal', 'summary': 'Concejal Principal del Municipio Junín.', 'order': 6},
        {'title': 'Sonia Mendoza', 'author': 'Concejal Principal', 'summary': 'Concejal Principal del Municipio Junín.', 'order': 7},
        {'title': 'Danny Sepúlveda', 'author': 'Concejal Principal', 'summary': 'Concejal Principal del Municipio Junín.', 'order': 8},
    ]

    councilors_map = {}
    for c in councilors_data:
        obj, _ = HomeContent.objects.update_or_create(
            title=c['title'],
            content_type='COUNCILOR',
            defaults={
                'slug': slugify(c['title']),
                'author': c['author'],
                'summary': c['summary'],
                'order': c['order'],
                'is_active': True,
                'status': 'PUBLISHED'
            }
        )
        councilors_map[c['title']] = obj

    # 2. Carga de las 15 Comisiones Permanentes de 2026
    commissions_data = [
        {'number': 1, 'name': 'Derechos Humanos, Justicia y Familia', 'president': 'Ninfa Correa', 'vice_president': 'Arfilio Jaimes', 'vocal': 'Danny Carrillo'},
        {'number': 2, 'name': 'Deporte y Juventud', 'president': 'Favio Omaña', 'vice_president': 'Arfilio Jaimes', 'vocal': 'Danny Sepúlveda'},
        {'number': 3, 'name': 'Educación y Cultura', 'president': 'Juana Parada', 'vice_president': 'Sonia Mendoza', 'vocal': 'Favio Omaña'},
        {'number': 4, 'name': 'Historia, Patrimonio y Turismo', 'president': 'Juana Parada', 'vice_president': 'Danny Sepúlveda', 'vocal': 'Sonia Mendoza'},
        {'number': 5, 'name': 'Ejidos', 'president': 'Sonia Mendoza', 'vice_president': 'Arfilio Jaimes', 'vocal': 'Danny Carrillo'},
        {'number': 6, 'name': 'Presupuesto', 'president': 'Danny Carrillo', 'vice_president': 'Sonia Mendoza', 'vocal': 'Arfilio Jaimes'},
        {'number': 7, 'name': 'Contraloría', 'president': 'Sonia Mendoza', 'vice_president': 'Favio Omaña', 'vocal': 'Juana Parada'},
        {'number': 8, 'name': 'Participación Ciudadana, Política y Frontera', 'president': 'Danny Sepúlveda', 'vice_president': 'Ninfa Correa', 'vocal': 'Sonia Mendoza'},
        {'number': 9, 'name': 'Legislación', 'president': 'Juana Parada', 'vice_president': 'Danny Sepúlveda', 'vocal': 'Danny Carrillo'},
        {'number': 10, 'name': 'Obras Públicas y Ordenamiento del Territorio', 'president': 'Arfilio Jaimes', 'vice_president': 'Juana Parada', 'vocal': 'Danny Sepúlveda'},
        {'number': 11, 'name': 'Servicios Públicos', 'president': 'Arfilio Jaimes', 'vice_president': 'Danny Carrillo', 'vocal': 'Ninfa Correa'},
        {'number': 12, 'name': 'Transporte', 'president': 'Arfilio Jaimes', 'vice_president': 'Favio Omaña', 'vocal': 'Juana Parada'},
        {'number': 13, 'name': 'Salud, Ambiente y Actividades Agrícolas y Pecuarias', 'president': 'Ninfa Correa', 'vice_president': 'Danny Carrillo', 'vocal': 'Juana Parada'},
        {'number': 14, 'name': 'Comunicación Social y Tecnología', 'president': 'Ninfa Correa', 'vice_president': 'Sonia Mendoza', 'vocal': 'Danny Sepúlveda'},
        {'number': 15, 'name': 'Eventos Públicos', 'president': 'Favio Omaña', 'vice_president': 'Juana Parada', 'vocal': 'Arfilio Jaimes'},
    ]

    for comm in commissions_data:
        Commission.objects.update_or_create(
            number=comm['number'],
            defaults={
                'name': comm['name'],
                'president': councilors_map.get(comm['president']),
                'vice_president': councilors_map.get(comm['vice_president']),
                'vocal': councilors_map.get(comm['vocal']),
                'description': f"Comisión Permanente N° {comm['number']} encargada del área de {comm['name']}."
            }
        )

    # 3. Carga Histórica de Legislaturas (I a VIII)
    legislatures_data = [
        {'title': 'I Legislatura', 'period': '1989 - 1992', 'mayor': 'Juan de Dios Cañas', 'order': 1, 'members': [{'name': 'Armando Bautista', 'party': 'AD'}, {'name': 'Sonia Hernán de Bastos', 'party': 'AD'}, {'name': 'José Omar Boada', 'party': 'AD'}, {'name': 'Luis Antonio Ruda', 'party': 'AD'}, {'name': 'Félix Campero Sánchez', 'party': 'AD'}, {'name': 'Juan Abello González', 'party': 'COPEI'}]},
        {'title': 'II Legislatura', 'period': '1992 - 1995', 'mayor': 'Pedro Fernández', 'order': 2, 'members': [{'name': 'Nelson Flores Galvis', 'party': 'COPEI'}, {'name': 'Evaristo Monsalve', 'party': 'COPEI'}, {'name': 'Juan Abello González', 'party': 'COPEI'}, {'name': 'Sonia Hernán de Bastos', 'party': 'AD'}, {'name': 'Marcos Moreno', 'party': 'AD'}]},
        {'title': 'III Legislatura', 'period': '1995 - 2000', 'mayor': 'Gonzalo Fuentes La Cruz', 'order': 3, 'members': [{'name': 'Gerardo Carrero', 'party': 'AD'}, {'name': 'Héctor Cabrera', 'party': 'AD'}, {'name': 'Marcos Moreno', 'party': 'AD'}, {'name': 'Pedro Chirinos', 'party': 'COPEI'}, {'name': 'Yaneth de Carrillo', 'party': 'COPEI'}]},
        {'title': 'IV Legislatura', 'period': '2000 - 2005', 'mayor': 'Luis Valladares', 'order': 4, 'members': [{'name': 'César Vera', 'party': 'MVR'}, {'name': 'Luis Sandoval', 'party': 'MVR'}, {'name': 'María Elena Ruiz', 'party': 'AD'}, {'name': 'Jorge Salcedo', 'party': 'COPEI'}]},
        {'title': 'V Legislatura', 'period': '2005 - 2013', 'mayor': 'Juan Peñaloza / Mercedes Chapeta', 'order': 5, 'members': [{'name': 'José Araujo', 'party': 'PSUV'}, {'name': 'Gladys Yáñez', 'party': 'PSUV'}, {'name': 'Yobel Sandoval', 'party': 'COPEI'}, {'name': 'Walter Chacón', 'party': 'AD'}]},
        {'title': 'VI Legislatura', 'period': '2013 - 2018', 'mayor': 'Yobel Sandoval', 'order': 6, 'members': [{'name': 'Danny Carrillo', 'party': 'COPEI'}, {'name': 'Sonia Mendoza', 'party': 'AD'}, {'name': 'Marcos Rincón', 'party': 'MUD'}, {'name': 'Johan Lizcano', 'party': 'MUD'}]},
        {'title': 'VII Legislatura', 'period': '2018 - 2021', 'mayor': 'Ángel Márquez', 'order': 7, 'members': [{'name': 'Herlany Rivas', 'party': 'PSUV'}, {'name': 'Rubén Manrique', 'party': 'PSUV'}, {'name': 'Elizabeth Martínez', 'party': 'PSUV'}]},
        {'title': 'VIII Legislatura', 'period': '2021 - Presente', 'mayor': 'Jackson Carrillo', 'is_current': True, 'order': 8, 'members': [{'name': 'Danny Carrillo', 'party': 'MUD'}, {'name': 'Favio Omaña', 'party': 'MUD'}, {'name': 'Juana Parada', 'party': 'MUD'}, {'name': 'Sonia Mendoza', 'party': 'MUD'}, {'name': 'Arfilio Jaimes', 'party': 'MUD'}, {'name': 'Ninfa Correa', 'party': 'MUD'}, {'name': 'Danny Sepúlveda', 'party': 'MUD'}]},
    ]

    for leg in legislatures_data:
        leg_obj, _ = Legislature.objects.update_or_create(
            title=leg['title'],
            defaults={
                'period': leg['period'],
                'mayor': leg['mayor'],
                'is_current': leg.get('is_current', False),
                'order': leg['order']
            }
        )
        leg_obj.members.all().delete()
        for member in leg['members']:
            Legislator.objects.create(
                legislature=leg_obj,
                name=member['name'],
                party=member['party']
            )


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260922_1508'),
    ]

    operations = [
        migrations.RunPython(populate_council_data, reverse_populate),
    ]