# Generated by Django 3.2.25 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260901_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarouselnews',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='news_pdfs/', verbose_name='Documento PDF de Respaldo'),
        ),
        migrations.AddField(
            model_name='homecarouselnews',
            name='show_pdf_inline',
            field=models.BooleanField(default=False, verbose_name='¿Mostrar PDF en visor interactivo?'),
        ),
    ]
