# Generated by Django 3.2.25 on 2026-09-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_council_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commissions/%Y/%m/', verbose_name='Imagen / Foto de la Comisión'),
        ),
    ]
