# Generated by Django 3.2.25 on 2026-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260903_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarouselnews',
            name='social_media_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Red Social (Instagram, Facebook, TikTok)'),
        ),
    ]
