# Generated by Django 3.2.25 on 2026-09-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commission_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
            ],
            options={
                'verbose_name': 'Junta Directiva',
                'verbose_name_plural': 'Junta Directiva',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='content_type',
            field=models.CharField(choices=[('NEWS', 'Noticia'), ('CHRONICLE', 'Crónica Digital'), ('CAROUSEL', 'Item de Carrusel'), ('ABOUT_US', 'Información Institucional'), ('COUNCILOR', 'Concejal / Directivo'), ('LEGISLATURE', 'Legislatura / Período'), ('BOARD', 'Junta Directiva')], default='NEWS', max_length=20, verbose_name='Tipo de Contenido'),
        ),
        migrations.DeleteModel(
            name='Legislator',
        ),
        migrations.DeleteModel(
            name='Legislature',
        ),
        migrations.CreateModel(
            name='Legislature',
            fields=[
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.homecontent',),
        ),
    ]
