# Generated by Django 3.2.25 on 2026-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homecarouselnews_social_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Crónica')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Resumen o Bajada')),
                ('content', models.TextField(verbose_name='Contenido Completo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chronicles_img/', verbose_name='Imagen Destacada')),
                ('author', models.CharField(default='Cronista Oficial', max_length=150, verbose_name='Autor / Cronista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Publicado?')),
            ],
            options={
                'verbose_name': 'Crónica',
                'verbose_name_plural': 'Crónicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
