# Generated by Django 3.2.25 on 2026-09-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chronicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MunicipalChronicle',
        ),
    ]
