# Generated by Django 3.2.25 on 2026-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_municipalchronicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstructuraDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo Institucional')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Titular')),
                ('descripcion', models.TextField(verbose_name='Descripción o Funciones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estructura_directiva/', verbose_name='Fotografía')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Estructura Directiva',
                'verbose_name_plural': 'Estructura Directiva',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título (Ej. I Legislatura)')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período (Ej. 1992 - 1995)')),
                ('descripcion_concejales', models.TextField(verbose_name='Concejales Integrantes / Datos')),
                ('es_actual', models.BooleanField(default=False, verbose_name='¿Es la legislatura actual?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Aparición')),
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
                'ordering': ['orden'],
            },
        ),
    ]
