# Generated by Django 3.2.25 on 2026-09-21 22:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ente Emisor',
                'verbose_name_plural': 'Entes Emisores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Número')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('is_extraordinary', models.BooleanField(default=False, verbose_name='¿Extraordinaria?')),
                ('emission_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Gaceta',
                'verbose_name_plural': 'Gacetas',
                'ordering': ['year', 'number'],
                'unique_together': {('number', 'year', 'is_extraordinary')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Borrado')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Número de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción / Reseña')),
                ('emission_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('is_approved', models.BooleanField(default=False, verbose_name='¿Aprobado?')),
                ('is_annulled', models.BooleanField(default=False, verbose_name='¿Anulado?')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdfs/%Y/%m/', verbose_name='Archivo PDF')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/images/%Y/%m/', verbose_name='Imagen')),
                ('other_entity_description', models.CharField(blank=True, max_length=100, verbose_name='Otro Ente (especificar)')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Tipo de Documento')),
                ('gazette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.gazette', verbose_name='Gaceta')),
                ('issuing_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.issuingentity', verbose_name='Ente Emisor')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-emission_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('is_annulled', True), ('is_approved', True), _negated=True), name='document_no_approved_and_annulled'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('number', 'gazette')},
        ),
    ]
