# Generated by Django 3.2.25 on 2026-10-01 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(('is_annulled', True), ('is_approved', True), _negated=True), name='document_no_approved_and_annulled'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('number', 'gazette')},
        ),
    ]
